### ISSUE TITLE
Create rosparam file that includes all adjustable parameters for inverted pendulum simulator

### ISSUE THREAD

**Issue by gabrieledcjr** [IRLL/inverted_pendulum#4]

**Comment by irwineffect** [comment]
I've made a few commits for this, see https://github.com/IRLL/Inverted-Pendulum/blob/ROS_Framework/ROSIntegration/src/inverted_pendulum/settings/sim_settings.yaml

**Comment by gabrieledcjr** [comment]
Is this done?

**Comment by irwineffect** [comment]
Yes, but I'd like you to confirm that I've done all the settings you would like, or if there's any others you want?

**Comment by irwineffect** [comment]
Done
